import Head from 'next/head'

const index = () => {
  return (
    <>
      <Head>
        <title>Contact section</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <p>
        Contact section
      </p>
    </>
  )
}

export default index
