import Header from '../components/header/header'
import Hero from '../components/hero/hero'
import Project from '../components/project/project'
import Aboutme from '../components/aboutme/aboutme'
import Contact from '../components/contact/contact'
import Footer from '../components/footer/footer'
import Head from 'next/head'

function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name='description' content='Generated by create next app'/>
        <link rel='icon' href='/favicon.svg'/>
      </Head>
      <Header />
      <Hero />
      <Project />
      <Aboutme />
      <Contact />
      <Footer />
    </>
  )
}

export default Home;
